Fix compilation error for lambdas in unused functions (#1016)
Previously, in certain cases, there could be a compilation error:
> var Lambda$ufa6f526451637135_0::$tmp_var is declared 
> but never written; please, provide a default value